name: Databricks CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
        echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV
        echo "DATABRICKS_CLUSTER_ID=${{ secrets.DATABRICKS_CLUSTER_ID }}" >> $GITHUB_ENV
        echo "DATABRICKS_ORG_ID=${{ secrets.DATABRICKS_ORG_ID }}" >> $GITHUB_ENV
        echo "DATABRICKS_PORT=${{ secrets.DATABRICKS_PORT }}" >> $GITHUB_ENV

    - name: Configure Databricks Connect
      run: |
        databricks-connect configure <<EOF
        ${{ secrets.DATABRICKS_HOST }}
        ${{ secrets.DATABRICKS_TOKEN }}
        ${{ secrets.DATABRICKS_CLUSTER_ID }}
        ${{ secrets.DATABRICKS_ORG_ID }}
        ${{ secrets.DATABRICKS_PORT }}
        EOF

    - name: Run tests
      run: |
        python -m pytest tests/ -v

    - name: Upload coverage
      uses: codecov/codecov-action@v3
